### ISSUE TITLE
[BUG] Build currently fails because Flex has moved its repository

### ISSUE THREAD

**Issue by bogdzn** [CMEPW/Smersh#153]
Following this guide, we should be able to get the build up and running again: https://symfony.com/blog/upgrade-flex-on-your-symfony-projects

Currently, the build fails when using the documentation's instruction (eg: `docker-compose up --build`) because it cannot curl `https://flex.symfony.com/versions.json`) as seen in the following screenshot 
![build-failure](https://user-images.githubusercontent.com/29751352/169574532-dee0cc87-6f84-4d34-a4cd-5386e5a1d6fb.png)

I have attempted to build locally `flex` and update manually flex, but I could not get it to work. We should look into it ASAP because new users cannot build smersh right now.

**Comment by AMolti** [comment]
Hi,

To solve this issue, you need to run: `docker-compose run php composer update` and rebuild.
I tried a lot of command, so I will do a clean install and post other modifications if necessary.

Best.

**Comment by bogdzn** [comment]
Awesome, I will try it this afternoon and let you know. Thank you very much !

**Comment by jenaye** [comment]
Hello @bogdzn, thank you for the link it was exactly the right thing to do

in my case i did 

`docker-compose run php composer global update` after 
`docker-compose run php composer update symfony/flex --no-plugins --no-scripts`

and regenerate jwt like this : 

```

docker-compose exec php sh -c '
    set -e
    apk add openssl
    mkdir -p config/jwt
    jwt_passphrase=${JWT_PASSPHRASE:-$(grep ''^JWT_PASSPHRASE='' .env | cut -f 2 -d ''='')}
    echo "$jwt_passphrase" | openssl genpkey -out config/jwt/private.pem -pass stdin -aes256 -algorithm rsa -pkeyopt rsa_keygen_bits:4096
    echo "$jwt_passphrase" | openssl pkey -in config/jwt/private.pem -passin stdin -out config/jwt/public.pem -pubout
    setfacl -R -m u:www-data:rX -m u:"$(whoami)":rwX config/jwt
    setfacl -dR -m u:www-data:rX -m u:"$(whoami)":rwX config/jwt
'
```

Because i had this message : 

![image](https://user-images.githubusercontent.com/15458329/175661507-cf032e08-4428-439e-8b54-8235c1b8c5fe.png)

Finaly i had this error : 

```
docker-compose logs -f api 
Attaching to smersh_api_1
api_1        | 2022/06/24 19:55:14 [crit] 6#6: *1 realpath() "/srv/api/public" failed (2: No such file or directory), client: 172.18.0.2, server: , request: "GET / HTTP/1.1", host: "api.smersh.lan"
``` 

and i fixed it using `docker-compose down` then `docker-compose up`
