### ISSUE TITLE
[New contributor] Implement a feature present in the to do list

### ISSUE THREAD

**Issue by RayMoDev** [CMEPW/Smersh#78]
Hi , I want to contribute to your project by making one of the features proposed in the to do list, can I have some more explanations on the project?

**Comment by jenaye** [comment]
Hi @RayMoDev, 
Sorry for the delay in responding, 
here is a small list of things that could be cool to do 


This project is pretty simple, during a penetration test each pentester keeps his notes locally, and you have to contact your colleague regularly to know what he found etc

Using smersh you are able to see where you are, what are the remaining targets to do, what vulnerability were found per domain and generate report ( you can use default template, or specify your ) 

and then we integrate a codimd so that the pentesters can exchange payloads or any other information

Todo list Smersh : 

* Better design in hacktivity tab and in all the application ahah
* Use Mercure to have real time interaction with other pentester/manager
* When you create new user in smersh, also create account on  CodiMD and Bitwarden using their API
* Translate all the app using ngx-translate like @anchis recommanded
*  You also can start to write tests ( end to end etc )
* Possiblity to show all missions linked to a client

**Comment by RayMoDev** [comment]
Thank you for the detailed answer @jenaye ,  I'm going to dive a little into the project and choose a task among those presents in your to do list and start to work on , I will come back to you if I have any other questions .

**Comment by RayMoDev** [comment]
Hi @jenaye , finally i decided to start with coding tests , Can i have more informations and details please ?

**Comment by Darkweak** [comment]
Hi @RayMoDev, thanks for your interest and the willingness to contribute to this project.  
IMO you can implement end-to-end cypress tests in the front-end part, it would be awesome.  
For the API part, we're working on the Behat and PHPUnit integration to be able to test it.  
(cc @jenaye)

**Comment by RayMoDev** [comment]
Hi @jenaye @Darkweak , so for the cypress tests what is the plan on mock APIs , create a mock backend or use a dedicated real hosted backend ?

**Comment by Darkweak** [comment]
Hi @RayMoDev, imo you may use a real hosted backend (such as the API with loaded fixtures). Then it could be great to run it through the CI (to be done) to ensure the non regression in this tool.
@jenaye what are you thinking about this?

**Comment by jenaye** [comment]
Yes it's probably the best thing to do  👍 
btw I recommend you to follow the steps in the link below, in order to launch only the API under docker, and install Angular on your host.
https://smersh.app/blog/2021/02/07/front-end-tips/

**Comment by RayMoDev** [comment]
@jenaye @Darkweak can i have a specific flow to test please

**Comment by jenaye** [comment]
Hey @RayMoDev  !
Well, you should do some tests like for example : 

`I am logged in as Admin, I try to access the "Missions" menu, I should see a table`


other example : 

`I try to access to /dashboard without JWT, I should be redirected to /login`

or 

`if I add a vulnerability, I should be redirected to the mission view, to see it appear`


it's this kind of tests that must be written on the Angular part, the API tests are currently being written

**Comment by RayMoDev** [comment]
@jenaye @Darkweak  i followed the steps in https://smersh.app/blog/2021/02/07/front-end-tips/ but when i login i have 
![image](https://user-images.githubusercontent.com/79284450/113146702-49d95f00-9230-11eb-8c4f-0fc3d9ca5933.png)

**Comment by jenaye** [comment]
Hello @RayMoDev  we will update it,  thank you

can you do this ?  in api folder copy .env-dist to .env then run `docker initialize`

**Comment by RayMoDev** [comment]
@jenaye i done that initially

**Comment by jenaye** [comment]
@RayMoDev  without logs it will be hard to help you, 
the simpliest way is probably : 

* delete current Smersh,  
* clone it
* copy .env-dist to .env in api folder
* then run `make upAll ` ( to install everything ) 

when its finish, you can stop like this `docker-compose down`
and after you can run  `docker-compose up api` to run only API

and if this don't work, show us the result of this command `docker-compose logs -f php`   ( sure php container need to be up )

**Comment by RayMoDev** [comment]
Hi @jenaye , it worked fine ! So i added some tests like those you advised me and opened a pull request , please review it
